export { default as Navbar } from './navbar/Navbar'
export { default as Header } from './header/Header'
export { default as Home } from './home/Home'
export { default as Register } from './register/Register'
export { default as Login } from './login/Login'
export { default as NotFound404 } from './404/NotFound404'